# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'


target 'MapTrip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps', '7.1.0'

  # Pods for MapTrip

  target 'MapTripTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapTripUITests' do
    # Pods for testing
  end

end
